version: '3.8' 

services:
  

  opendj:
    build:
      context: ./opendj
      dockerfile: ./Dockerfile
    container_name: opendj
    volumes:
      - ./data/opendj:/usr/opendj/config
    ports:  
      - "1389:1389"
      - "4444:4444"
      - "1636:1636"      
    user: root
    networks:
      - my-net

  openam:
    build:
      context: ./openam
      dockerfile: ./Dockerfile
    container_name: openam
    volumes:
      - ./data/openam:/usr/openam/config
    ports:
      - "8080:8080"
      - "1689:1689"
      - "4445:4444"
      - "50389:50389"
    user: root
    networks:
      - my-net
    extra_hosts:
      - "openam.test.com:127.0.0.1"
    depends_on: 
      - opendj
    links:
      - opendj

networks:
  my-net:
    driver: bridge
      