#!/bin/bash

set -e

echo "Before executing configurator-tool"

nohup /usr/local/tomcat/bin/catalina.sh run >> nohup.out 2>&1 &

#sleep 15

bash /tmp/wait-for.sh localhost:8080 -t 60 -s -- java -jar /usr/openam/ssoconfiguratortools/openam-configurator-tool-14.5.1.jar -file /usr/openam/ssoconfiguratortools/config.properties --acceptLicense -y

echo "After executing configurator-tool"

tail -f nohup.out